'use client';
import { useMemo } from 'react';import { usePublicRows } from '@/hooks/usePublicRows';import { usePublicSection } from '@/hooks/usePublicSection';import { usePublicNavigation } from '@/hooks/usePublicNavigation';import { useThemeSettings } from '@/hooks/useThemeSettings';import { cmsFallbackSections } from '@/lib/data';
type Row={area:string;component:string;table:string;field:string;value:string;origin:'client-runtime'|'fallback'|'build-static'|'erro';state:string};
const short=(v:any)=>String(v??'').slice(0,160);
const readOrigin=(loading:boolean,error:string|null):Row['origin']=>error?'erro':loading?'fallback':'client-runtime';
function SectionAudit({prefix,component,sectionKey,fields}:{prefix:string;component:string;sectionKey:string;fields:string[]}){const h=usePublicSection(sectionKey);const rows=fields.map(k=>({area:`${prefix} ${k}`,component,table:'page_sections + section_fields',field:`${sectionKey}.${k}`,value:short(h.data[k])||'vazio',origin:readOrigin(h.loading,h.error),state:short(h.data[k])?'CMS/fallback resolvido':'vazio'}));return <AuditRows rows={rows}/>}
function AuditRows({rows}:{rows:Row[]}){return <>{rows.map((r,i)=><tr key={`${r.area}-${i}`} className="odd:bg-zinc-950 even:bg-zinc-900/60"><td className="border border-white/10 p-3 font-semibold">{r.area}</td><td className="border border-white/10 p-3">{r.component}</td><td className="border border-white/10 p-3">{r.table}</td><td className="border border-white/10 p-3">{r.field}</td><td className="border border-white/10 p-3 text-zinc-300">{r.value||'vazio'}</td><td className="border border-white/10 p-3"><span className={r.origin==='client-runtime'?'text-emerald-300':r.origin==='erro'?'text-red-300':'text-yellow-300'}>{r.origin}</span></td><td className="border border-white/10 p-3 text-zinc-300">{r.state}</td></tr>)}</>}
export function CmsAuditRuntime(){const theme=useThemeSettings();const home=usePublicRows('page_sections',cmsFallbackSections.filter(s=>s.page_slug==='home'),q=>q.eq('page_slug','home').eq('is_active',true).order('order_index'));const fiti=usePublicRows('page_sections',cmsFallbackSections.filter(s=>s.page_slug==='fiti'),q=>q.eq('page_slug','fiti').eq('is_active',true).order('order_index'));const main=usePublicNavigation('main_menu');const footer=usePublicNavigation('footer_menu');const fitiMenu=usePublicNavigation('fiti_menu');const collections=[['Homepage Notícias','News','news','published=true',usePublicRows('news',[],q=>q.eq('published',true).order('created_at',{ascending:false}))],['FITI Programação','Program','fiti_program','is_active=true',usePublicRows('fiti_program',[],q=>q.eq('is_active',true).order('date').order('time'))],['FITI Companhias','Companies','fiti_companies','is_active=true',usePublicRows('fiti_companies',[],q=>q.eq('is_active',true).order('order_index'))],['FITI Oficinas','Workshops','fiti_workshops','is_active=true',usePublicRows('fiti_workshops',[],q=>q.eq('is_active',true).order('date'))],['FITI Arquivo','FitiArchive','fiti_archive','is_active=true',usePublicRows('fiti_archive',[],q=>q.eq('is_active',true).order('year',{ascending:false}))],['Redes sociais','Footer','social_links','is_active=true',usePublicRows('social_links',[],q=>q.eq('is_active',true).order('order_index'))]] as const;const rows:Row[]=useMemo(()=>[
{area:'Theme settings',component:'DynamicBackground/Footer/WhatsApp',table:'theme_settings',field:'value/value_json',value:short(JSON.stringify(theme.settings)),origin:readOrigin(theme.loading,theme.error),state:theme.error||'value tem prioridade sobre value_json vazio'},
{area:'Homepage secções',component:'PublicHome',table:'page_sections',field:"page_slug='home'",value:home.data.map(s=>s.section_key).join(', '),origin:readOrigin(home.loading,home.error),state:'ordem lida no browser'},
{area:'FITI secções',component:'PublicFiti',table:'page_sections',field:"page_slug='fiti'",value:fiti.data.map(s=>s.section_key).join(', '),origin:readOrigin(fiti.loading,fiti.error),state:'ordem lida no browser'},
{area:'Navbar menu',component:'Navbar',table:'navigation_items',field:"location='main_menu'",value:main.data.map(i=>i.label).join(', '),origin:readOrigin(main.loading,main.error),state:'sem duplicados label+url'},
{area:'Footer menu',component:'Footer',table:'navigation_items',field:"location='footer_menu'",value:footer.data.map(i=>i.label).join(', '),origin:readOrigin(footer.loading,footer.error),state:'runtime'},
{area:'FITI menu',component:'PublicFiti',table:'navigation_items',field:"location='fiti_menu'",value:fitiMenu.data.map(i=>i.label).join(', '),origin:readOrigin(fitiMenu.loading,fitiMenu.error),state:'runtime'},
], [theme.settings,theme.loading,theme.error,home.data,home.loading,home.error,fiti.data,fiti.loading,fiti.error,main.data,main.loading,main.error,footer.data,footer.loading,footer.error,fitiMenu.data,fitiMenu.loading,fitiMenu.error]);return <main className="min-h-screen bg-black p-6 text-white"><h1 className="font-display text-4xl text-sun">Auditoria CMS → Site Público</h1><p className="mt-2 text-zinc-300">Esta auditoria corre no browser. Conteúdo editável deve aparecer com origem <b>client-runtime</b>; durante carregamento ou falha usa fallback institucional.</p><div className="mt-6 overflow-x-auto"><table className="min-w-[1100px] border-collapse text-left text-sm"><thead><tr className="bg-zinc-900 text-sun">{['Área','Componente','Tabela','Campo/chave','Valor resolvido','Origem da leitura','Estado'].map(h=><th key={h} className="border border-white/10 p-3">{h}</th>)}</tr></thead><tbody><AuditRows rows={rows}/><SectionAudit prefix="Homepage Hero" component="Hero" sectionKey="home_hero" fields={['eyebrow','title','subtitle','description','primary_button_label','primary_button_url','secondary_button_label','secondary_button_url']}/><SectionAudit prefix="Homepage Quem Somos" component="About" sectionKey="home_about" fields={['section_title','section_text']}/><SectionAudit prefix="Homepage O que fazemos" component="WhatWeDo" sectionKey="home_what_we_do" fields={['section_title','cards']}/><SectionAudit prefix="FITI Hero" component="FitiHero" sectionKey="fiti_hero" fields={['eyebrow','title','subtitle','description']}/><SectionAudit prefix="FITI Sobre" component="FitiAbout" sectionKey="fiti_about" fields={['section_title','section_text']}/><SectionAudit prefix="FITI Imprensa" component="PressKit" sectionKey="fiti_press" fields={['section_title','section_text','cards']}/><AuditRows rows={collections.map(([area,component,table,field,h])=>({area,component,table,field,value:`${h.data.length} item(s)`,origin:readOrigin(h.loading,h.error),state:h.data.length?'dados disponíveis':'vazio: mostrar mensagem elegante'}))}/></tbody></table></div></main>}
