export const siteSettings = {
  dominantColor: '#F7B500',
  lightYellow: '#FFD166',
  orange: '#F97316',
  animatedBackground: true,
  backgroundIntensity: 'medium',
  whatsapp: 'https://wa.me/?text=Olá%20Associação%20Cultural%20Girassol',
  email: 'contacto@associacaoculturalgirassol.org',
  seoTitle: 'Associação Cultural Girassol',
  seoDescription: 'Teatro, juventude, memória e transformação cultural em Moçambique.',
  footerText: 'Associação Cultural Girassol — teatro, juventude, memória e transformação cultural em Moçambique.',
};
export const mandatoryFitiPhrase = 'FITI – Festival Internacional Teatro de Inverno, uma iniciativa da Associação Cultural Girassol.';
export const hero = { title:'Associação Cultural Girassol', subtitle:'Teatro, juventude, memória e transformação cultural em Moçambique.', support:'Há mais de três décadas, a Associação Cultural Girassol promove a criação artística, a formação teatral, o intercâmbio cultural e a participação comunitária, usando o teatro como ferramenta de expressão, cidadania e transformação social.', primary:'Conheça a Associação', secondary:'Ver FITI' };
export const aboutText = ['A Associação Cultural Girassol é uma organização cultural juvenil moçambicana dedicada à promoção do teatro, da formação artística, do intercâmbio cultural e da participação comunitária.','Criada a partir do Grupo de Teatro Girassol, nascido em 1987, a Associação construiu uma trajectória marcada pela formação de actores, produção de espectáculos, circulação artística, acções sociais e apoio a grupos culturais emergentes.','Ao longo dos anos, o Girassol afirmou-se como um espaço de criação, aprendizagem e encontro entre artistas, jovens, comunidades e instituições culturais, promovendo o teatro como ferramenta de expressão, cidadania, diálogo e transformação social.'];
export const missionVision = { mission:'Promover o teatro e as artes cénicas como instrumentos de educação, participação juvenil, intercâmbio cultural, inclusão social e desenvolvimento comunitário.', vision:'Ser uma referência nacional e internacional na promoção do teatro, da formação artística e da circulação cultural, contribuindo para uma sociedade mais criativa, participativa e consciente do valor da cultura.', values:['Criatividade','Inclusão','Juventude','Memória','Intercâmbio','Cidadania','Profissionalismo','Transformação social'] };
export const timeline = [{year:'1987',title:'Nascimento do Grupo de Teatro Girassol',description:'Reunião de crianças e jovens de diferentes zonas da cidade de Maputo em torno da criação teatral.'},{year:'2004',title:'Reconhecimento jurídico da Associação Cultural Girassol',description:'Consolidação da sua missão cultural, educativa e comunitária.'},{year:'2007',title:'Consolidação do Teatro d’Inverno',description:'Afirmação de um espaço de intercâmbio entre grupos artísticos, jovens criadores e comunidades.'},{year:'2009',title:'Expansão das acções de formação teatral',description:'Oficinas em dramaturgia, representação, encenação, som, luz e gestão de grupos culturais.'},{year:'2010',title:'Fortalecimento da intervenção comunitária',description:'Teatro como ferramenta de debate social, educação, cidadania e intervenção comunitária.'},{year:'Actualidade',title:'Afirmação do FITI',description:'O Festival Internacional Teatro de Inverno é o principal projecto da Associação e uma plataforma de circulação, formação e intercâmbio artístico.'}];
export const whatWeDo = [{title:'Teatro',description:'Produzimos, promovemos e apoiamos espectáculos teatrais, incentivando a criação artística e a valorização das artes cénicas.'},{title:'Formação artística',description:'Realizamos oficinas, masterclasses e acções formativas para actores, encenadores, técnicos, produtores e jovens criadores.'},{title:'Intercâmbio cultural',description:'Criamos pontes entre artistas, grupos, instituições e comunidades, promovendo encontros nacionais e internacionais.'},{title:'Festivais',description:'Organizamos plataformas de apresentação, circulação e diálogo artístico, com destaque para o FITI – Festival Internacional Teatro de Inverno.'},{title:'Acção social',description:'Desenvolvemos actividades culturais e comunitárias que aproximam a arte da educação, da cidadania e da transformação social.'},{title:'Educação e cidadania',description:'Usamos o teatro como ferramenta de reflexão, sensibilização e participação activa de jovens e comunidades.'}];
export const projects = [{title:'FITI – Festival Internacional Teatro de Inverno',description:'Principal projecto da Associação Cultural Girassol, o FITI é uma plataforma de circulação, formação, intercâmbio e valorização do teatro em Moçambique e no mundo.',link:'/fiti'},{title:'Grupo de Teatro Girassol',description:'Espaço de criação teatral, formação de actores e produção artística, responsável por marcar a origem e a identidade cultural da Associação.'},{title:'Chapa da Malta',description:'Projecto de edutretenimento e intervenção comunitária voltado para jovens, cidadania, saúde, educação, cultura e participação social.'},{title:'Teatro nas Escolas',description:'Acções de apresentação, formação e debate em contexto escolar, aproximando estudantes das artes cénicas e de temas sociais relevantes.'},{title:'Oficinas e Formação',description:'Programas de capacitação em representação, dramaturgia, encenação, produção, som, luz e gestão cultural.'}];
export const impactStats = ['Mais de 30 anos de trajectória cultural','Mais de 20 edições do FITI','Artistas, jovens e grupos culturais envolvidos','Espectáculos, oficinas e debates realizados','Comunidades, escolas e instituições alcançadas','Intercâmbios nacionais e internacionais promovidos'];
export const gallery = ['Associação','FITI','Teatro','Formação','Arquivo','Comunidade'].map((category)=>({title:`Memória visual — ${category}`,category,description:'Registo institucional disponível para actualização no painel de gestão.',imageUrl:''}));
export const news = [{title:'Agenda cultural em actualização',category:'Notícias',date:'Actualidade',summary:'Em breve serão publicados comunicados, actividades e informações oficiais da Associação Cultural Girassol.'},{title:'Informações institucionais',category:'Comunicação',date:'Actualidade',summary:'O painel de gestão permite actualizar notícias, imagens, parceiros e conteúdos de divulgação.'}];
export const partners = ['Parceiros institucionais','Apoios culturais','Parceiros técnicos','Comunicação e comunidade'].map(name=>({name,category:name,logoUrl:'',link:''}));
export const fitiHero = { title:'FITI – Festival Internacional Teatro de Inverno', subtitle:'Uma plataforma de teatro, intercâmbio, formação e circulação artística.', support:'O FITI reúne companhias, criadores, formadores, programadores e públicos em torno das artes cénicas, fortalecendo o teatro moçambicano e a sua ligação com o mundo.' };
export const fitiAbout = ['O FITI – Festival Internacional Teatro de Inverno é o principal projecto da Associação Cultural Girassol. Nascido como Teatro d’Inverno, o festival tornou-se uma plataforma de circulação, formação e intercâmbio artístico, reunindo companhias de teatro de Moçambique e de outros países.','Mais do que um festival, o FITI é um espaço de encontro entre gerações, linguagens, territórios e públicos, contribuindo para a afirmação do teatro moçambicano e para a valorização das artes cénicas no país.'];
export const currentEdition = {year:'Edição Actual',theme:'Tema em preparação',dates:'Datas em actualização',locations:'Locais em actualização',countries:'Países participantes em confirmação',description:'A edição actual do FITI celebra o teatro como espaço de criação, encontro e transformação. A programação reúne espectáculos, oficinas, debates, teatro de rua, teatro comunitário, propostas infantis e actividades formativas.',curatorial:'Texto curatorial em preparação pela organização.'};
export const program = [{date:'Em actualização',time:'Horário a anunciar',title:'Programação em actualização',company:'Companhias a anunciar',country:'',venue:'Locais a anunciar',category:'Teatro adulto',synopsis:'Em breve serão anunciados os espectáculos, companhias, locais e horários da edição actual.',duration:'',ageRating:''}];
export const companies = [{name:'Companhias e artistas em actualização',country:'Moçambique e países convidados',description:'Conheça aqui as companhias, artistas e criadores que farão parte da programação do FITI assim que a selecção oficial for anunciada.',show:'Programação a anunciar'}];
export const workshops = [{title:'Formação em actualização',trainer:'Formadores a anunciar',date:'Datas a anunciar',time:'Horários a anunciar',venue:'Locais a anunciar',vacancies:'Sujeitas a inscrição',target:'Actores, técnicos, produtores, estudantes e jovens criadores'}];
export const archive = ['2025','2024','2023'].map(year=>({year,theme:'Memória FITI',dates:'Arquivo em organização',locations:'Maputo e espaços parceiros',countries:'Moçambique e convidados internacionais',companies:'Companhias participantes documentadas no arquivo institucional'}));

import type { MediaAsset, NavigationItem, Page, PageSection, SectionField, ThemeSettings } from '@/types/cms';
export const cmsEmptyState = 'Conteúdo em actualização. Em breve serão publicadas novas informações.';
export const cmsFallbackPages: Page[] = [
  {id:'home',slug:'home',title:'Associação Cultural Girassol',seo_title:siteSettings.seoTitle,seo_description:siteSettings.seoDescription,is_published:true},
  {id:'fiti',slug:'fiti',title:'FITI – Festival Internacional Teatro de Inverno',seo_title:'FITI – Festival Internacional Teatro de Inverno',seo_description:'Festival internacional de teatro promovido pela Associação Cultural Girassol.',is_published:true},
];
const homeKeys=['home_hero','home_about','home_mission_vision','home_timeline','home_what_we_do','home_projects','home_impact','home_gallery','home_news','home_partners','home_contact'];
const fitiKeys=['fiti_hero','fiti_about','fiti_current_edition','fiti_program','fiti_companies','fiti_workshops','fiti_tickets','fiti_archive','fiti_partners','fiti_press','fiti_contact','fiti_forms'];
const sectionNames:Record<string,string>={home_hero:'Destaque principal',home_about:'Quem somos',home_mission_vision:'Missão, visão e valores',home_timeline:'História',home_what_we_do:'O que fazemos',home_projects:'Projectos',home_impact:'Impacto',home_gallery:'Galeria',home_news:'Notícias',home_partners:'Parceiros',home_contact:'Contactos',fiti_hero:'Destaque FITI',fiti_about:'Sobre o FITI',fiti_current_edition:'Edição actual',fiti_program:'Programação FITI',fiti_companies:'Companhias FITI',fiti_workshops:'Oficinas FITI',fiti_tickets:'Bilhetes e reservas',fiti_archive:'Arquivo FITI',fiti_partners:'Parceiros FITI',fiti_press:'Imprensa FITI',fiti_contact:'Contactos FITI',fiti_forms:'Inscrições e pedidos FITI'};
export const cmsFallbackSections: PageSection[] = [...homeKeys.map((key,index)=>({id:key,page_slug:'home',section_key:key,section_name:sectionNames[key]??key.replaceAll('_',' '),section_type:key.split('_').slice(1).join('_'),order_index:index+1,is_active:true,settings:{editable:true}})),...fitiKeys.map((key,index)=>({id:key,page_slug:'fiti',section_key:key,section_name:key.replaceAll('_',' '),section_type:key.split('_').slice(1).join('_'),order_index:index+1,is_active:true,settings:{editable:true}}))];
const field=(section:string,key:string,label:string,value:string,type:SectionField['field_type']='text',order=1):SectionField=>({id:`${section}-${key}`,section_id:section,field_key:key,field_label:label,field_type:type,field_value:value,order_index:order});
export const cmsFallbackFields: Record<string, SectionField[]> = {
  home_hero:[field('home_hero','eyebrow','Chamada','Teatro • juventude • memória'),field('home_hero','title','Título',hero.title,'textarea',2),field('home_hero','subtitle','Subtítulo',hero.subtitle,'textarea',3),field('home_hero','description','Descrição',hero.support,'textarea',4),field('home_hero','primary_button_text','Botão principal',hero.primary,'text',5),field('home_hero','primary_button_link','Link principal','#quem-somos','url',6),field('home_hero','secondary_button_text','Botão secundário',hero.secondary,'text',7),field('home_hero','secondary_button_link','Link secundário','/fiti','url',8)],
  fiti_hero:[field('fiti_hero','title','Título',fitiHero.title,'textarea'),field('fiti_hero','subtitle','Subtítulo',fitiHero.subtitle,'textarea',2),field('fiti_hero','description','Descrição',fitiHero.support,'textarea',3)],
  fiti_program:[field('fiti_program','section_title','Título','Programação FITI'),field('fiti_program','section_subtitle','Subtítulo','Espectáculos, encontros e actividades da edição actual.','textarea',2),field('fiti_program','empty_state_text','Mensagem sem conteúdos',cmsEmptyState,'textarea',3),field('fiti_program','filters_enabled','Filtros activos','true','boolean',4),field('fiti_program','layout_style','Estilo','cards','select',5),field('fiti_program','button_text','Texto do botão','Ver detalhes','text',6)],
};
for (const section of cmsFallbackSections) cmsFallbackFields[section.section_key] ??= [field(section.section_key,'section_title','Título da secção',section.section_name),field(section.section_key,'section_text','Texto da secção',cmsEmptyState,'textarea',2)];
export const cmsFallbackTheme: ThemeSettings = {primary_color:'#F7B500',secondary_color:'#111111',accent_color:'#F97316',background_color:'#050505',text_color:'#ffffff',card_color:'#18181b',button_style:'rounded',dominant_yellow_enabled:true,animated_background_enabled:true,animated_logo_enabled:true,background_motion_intensity:'medium',particles_enabled:true,stage_lights_enabled:true,border_radius:'1.5rem',font_heading:'Playfair Display',font_body:'Inter',background_type:'mixed',gradient_from:'#F7B500',gradient_to:'#050505',background_image_url:'',background_video_url:'',site_logo_url:'',site_logo_alt:'Associação Cultural Girassol',fiti_logo_url:'',fiti_logo_alt:'FITI – Festival Internacional Teatro de Inverno',favicon_url:'',footer_logo_url:'',navbar_logo_url:'',hero_logo_url:'',animated_logo_url:'',animated_logo_opacity:0.08,animated_logo_speed:42,overlay_opacity:0.55};
export const cmsFallbackNavigation: NavigationItem[] = [
  ...[['#inicio','Início'],['#quem-somos','Quem Somos'],['#historia','História'],['#projectos','Projectos'],['#impacto','Impacto'],['#galeria','Galeria'],['#noticias','Notícias'],['#parceiros','Parceiros'],['#contacto','Contacto'],['/fiti','FITI']].map(([url,label],i)=>({id:`main-${i}`,location:'main_menu' as const,label,url,order_index:i+1,is_active:true,is_external:false})),
  ...[['/fiti#sobre','Sobre'],['/fiti#programacao','Programação'],['/fiti#companhias','Companhias'],['/fiti#oficinas','Oficinas'],['/fiti#arquivo','Arquivo'],['/fiti#contacto','Contacto']].map(([url,label],i)=>({id:`fiti-${i}`,location:'fiti_menu' as const,label,url,order_index:i+1,is_active:true,is_external:false})),
  ...[['/','Associação'],['/fiti','FITI'],['/#contacto','Contacto']].map(([url,label],i)=>({id:`footer-${i}`,location:'footer_menu' as const,label,url,order_index:i+1,is_active:true,is_external:false})),
];
export const cmsFallbackMedia: MediaAsset[] = [];
